Implemented distribution_plot() and count_plot()
loosolab/UROPA pull request #16
Opened 2022-09-27 15:16 UTC by Mfkessler

First version of plotting functions, written during Hackathon 09.2022

2022-09-29 09:33 UTC, hschult requested changes

2022-09-29 09:37 UTC, hschult commented
Overall please add some comments to your code. It is a good habit to add a comment every few lines. Always try to write your code in a way that you can easily come back in a few months and understand what you did.

2022-10-14 08:14 UTC, hschult requested changes

2022-10-14 08:14 UTC, hschult commented on uropa/visualization.py
> +    match kind:
Please add this version restriction to setup.py. Also, add your dependencies to `install_requires`.

2022-10-14 08:44 UTC, hschult requested changes

2022-10-14 08:44 UTC, hschult commented on uropa/visualization.py
> +            print(f"{kind} not supported. Consider using one of the supported plots (histogram, boxplot or violin).")
Please, raise an error. Don't use `exit` for this.

2022-10-14 10:50 UTC, Mfkessler commented on uropa/visualization.py
> +    sns.set(style = "darkgrid")
actually it does not seem to be default using jupyter notebook, so I added it again.

2022-10-19 14:39 UTC, hschult requested changes

2022-10-19 14:39 UTC, hschult commented on uropa/visualization.py
> +def peak_count_plot(table, var="feature", peak_type="exon", group_by=["peak_chr", "peak_start", "peak_end", "peak_strand"], stacked=False, color_by=None, title=None, output=None, dpi=300):
check parameters `var, feature, peak_type, group_by, color_by`. Also, I can't select `nan` with `peak_type` as `nan` can only be checked with `.isna()`.

2022-10-19 14:39 UTC, hschult commented on uropa/visualization.py
> +        df = df.groupby([peak_type, color_by]).size().to_frame(
Why did you split the line? If it was due to length consider this:
https://stackoverflow.com/a/33944618/19870975

2022-10-19 14:39 UTC, hschult commented on uropa/visualization.py
> +            pcPlot = df.pivot(index=peak_type, columns=color_by, values="count").plot(
See comment above

2022-10-19 14:39 UTC, hschult commented on uropa/visualization.py
> +        plt.savefig(output, dpi=dpi)
`dpi` has only effect on the saved image. Please change that so it will always apply.

2022-10-21 09:08 UTC, hschult approved these changes
Looks good to me. We can merge now.
Good job 🥳

2022-10-21 09:10 UTC, merged